[build]
  command = "npm run build"
  publish = ".next"

# Enable Next.js functionality on Netlify
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Handle routing for Next.js app
[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  conditions = {Path = "/_next/static/**"}

# All other routes go through index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200